import type { WallhavenSettings } from '$lib/types/wallhaven';

export type Color = {
	hex: string;
};

export type PaletteData = {
	id: string;
	name: string;
	palette: Color[];
	createdAt: string;
	isSystem?: boolean;
};

export type SavePaletteRequest = {
	name: string;
	palette: Color[];
};

export type GetPalettesResponse = {
	palettes: PaletteData[];
};

export type SavePaletteResult = {
	message: string;
	name: string;
};

export type NamedColor = {
	name: string;
	hex: string;
};

export type Selector = {
	id: string;
	color: string;
	selected: boolean;
	selection?: { x: number; y: number; w: number; h: number };
};

export type WorkspaceData = {
	id: string;
	name: string;
	imageData: string;
	colors?: Color[];
	selectors?: Selector[];
	activeSelectorId?: string;
	luminosity?: number;
	nearest?: number;
	power?: number;
	maxDistance?: number;
	wallhavenSettings?: WallhavenSettings;
	shareToken?: string | null;
	createdAt: string;
};

export type SaveWorkspaceRequest = {
	name: string;
	imageData: string;
	colors: Color[];
	selectors: Selector[];
	activeSelectorId: string;
	luminosity: number;
	nearest: number;
	power: number;
	maxDistance: number;
	wallhavenSettings?: WallhavenSettings;
};

export type GetWorkspacesResponse = {
	workspaces: WorkspaceData[];
};

export type SaveWorkspaceResult = {
	message: string;
	name: string;
};

export type ShareWorkspaceResult = {
	shareToken: string;
	shareUrl: string;
};

// Theme types
export const VSCodeThemeSchema = 'vscode://schemas/color-theme' as const;

export type FontStyle = 'normal' | 'italic' | 'oblique';

export type VSCodeTokenSettings = {
	foreground?: string;
	background?: string;
	fontStyle?: string;
};

export type VSCodeTokenColor = {
	scope: string[];
	settings: VSCodeTokenSettings;
};

export type VSCodeThemeColors = {
	'editor.background': string;
	'editor.foreground': string;
	foreground: string;
	disabledForeground: string;
	focusBorder: string;
	descriptionForeground: string;
	errorForeground: string;
	'icon.foreground': string;
	'widget.border': string;
	'selection.background': string;
	'sash.hoverBorder': string;
	'activityBar.background': string;
	'activityBar.foreground': string;
	'activityBar.activeBorder': string;
	'activityBarBadge.background': string;
	'activityBarBadge.foreground': string;
	'sideBar.background': string;
	'sideBar.foreground': string;
	'sideBar.border': string;
	'sideBarTitle.foreground': string;
	'statusBar.background': string;
	'statusBar.foreground': string;
	'statusBar.noFolderBackground': string;
	'statusBar.debuggingBackground': string;
	'titleBar.activeBackground': string;
	'titleBar.activeForeground': string;
	'titleBar.inactiveBackground': string;
	'titleBar.inactiveForeground': string;
	'tab.activeBackground': string;
	'tab.activeForeground': string;
	'tab.inactiveBackground': string;
	'tab.inactiveForeground': string;
	'tab.activeBorder': string;
	'tab.border': string;
	'editorGroupHeader.tabsBackground': string;
	'panel.background': string;
	'panel.border': string;
	'panelTitle.activeBorder': string;
	'terminal.foreground': string;
	'terminal.ansiBlack': string;
	'terminal.ansiRed': string;
	'terminal.ansiGreen': string;
	'terminal.ansiYellow': string;
	'terminal.ansiBlue': string;
	'terminal.ansiMagenta': string;
	'terminal.ansiCyan': string;
	'terminal.ansiWhite': string;
	'terminal.ansiBrightBlack': string;
	'terminal.ansiBrightRed': string;
	'terminal.ansiBrightGreen': string;
	'terminal.ansiBrightYellow': string;
	'terminal.ansiBrightBlue': string;
	'terminal.ansiBrightMagenta': string;
	'terminal.ansiBrightCyan': string;
	'terminal.ansiBrightWhite': string;
	'input.background': string;
	'input.border': string;
	'input.foreground': string;
	'input.placeholderForeground': string;
	'inputOption.activeBorder': string;
	'inputOption.activeBackground': string;
	'inputOption.activeForeground': string;
	'inputValidation.errorBackground': string;
	'inputValidation.errorBorder': string;
	'inputValidation.errorForeground': string;
	'inputValidation.warningBackground': string;
	'inputValidation.warningBorder': string;
	'inputValidation.warningForeground': string;
	'inputValidation.infoBackground': string;
	'inputValidation.infoBorder': string;
	'inputValidation.infoForeground': string;
	'dropdown.background': string;
	'dropdown.foreground': string;
	'dropdown.border': string;
	'dropdown.listBackground': string;
	'quickInput.background': string;
	'quickInput.foreground': string;
	'quickInputList.focusBackground': string;
	'quickInputList.focusForeground': string;
	'quickInputList.focusIconForeground': string;
	'quickInputTitle.background': string;
	'list.activeSelectionBackground': string;
	'list.activeSelectionForeground': string;
	'list.inactiveSelectionBackground': string;
	'list.hoverBackground': string;
	'list.focusBackground': string;
	'list.highlightForeground': string;
	'pickerGroup.foreground': string;
	'pickerGroup.border': string;
	'button.background': string;
	'button.foreground': string;
	'button.hoverBackground': string;
	'button.secondaryBackground': string;
	'button.secondaryForeground': string;
	'button.secondaryHoverBackground': string;
	'badge.background': string;
	'badge.foreground': string;
	'breadcrumb.foreground': string;
	'breadcrumb.focusForeground': string;
	'breadcrumb.activeSelectionForeground': string;
	'breadcrumb.background': string;
	'scrollbarSlider.background': string;
	'scrollbarSlider.hoverBackground': string;
	'scrollbarSlider.activeBackground': string;
	'editorLineNumber.foreground': string;
	'editorLineNumber.activeForeground': string;
	'editorCursor.foreground': string;
	'editor.selectionBackground': string;
	'editor.inactiveSelectionBackground': string;
	'editor.findMatchBackground': string;
	'editor.findMatchHighlightBackground': string;
	'editorBracketMatch.background': string;
	'editorBracketMatch.border': string;
	'editorBracketHighlight.foreground1': string;
	'editorBracketHighlight.foreground2': string;
	'editorBracketHighlight.foreground3': string;
	'editorBracketHighlight.foreground4': string;
	'editorBracketHighlight.foreground5': string;
	'editorBracketHighlight.foreground6': string;
	'editorBracketPairGuide.activeBackground1': string;
	'editorBracketPairGuide.activeBackground2': string;
	'editorBracketPairGuide.activeBackground3': string;
	'editorBracketPairGuide.activeBackground4': string;
	'editorBracketPairGuide.activeBackground5': string;
	'editorBracketPairGuide.activeBackground6': string;
	'editorBracketPairGuide.background1': string;
	'editorBracketPairGuide.background2': string;
	'editorBracketPairGuide.background3': string;
	'editorBracketPairGuide.background4': string;
	'editorBracketPairGuide.background5': string;
	'editorBracketPairGuide.background6': string;
	'editorWhitespace.foreground': string;
	'editorWidget.background': string;
	'editorWidget.foreground': string;
	'editorWidget.border': string;
	'editorWidget.resizeBorder': string;
	'editorSuggestWidget.background': string;
	'editorSuggestWidget.foreground': string;
	'editorSuggestWidget.border': string;
	'editorSuggestWidget.highlightForeground': string;
	'editorSuggestWidget.focusHighlightForeground': string;
	'editorSuggestWidget.selectedBackground': string;
	'editorSuggestWidget.selectedForeground': string;
	'editorSuggestWidget.selectedIconForeground': string;
	'editorHoverWidget.background': string;
	'editorHoverWidget.foreground': string;
	'editorHoverWidget.border': string;
	'editorHoverWidget.highlightForeground': string;
	'editorHoverWidget.statusBarBackground': string;
	'editorError.foreground': string;
	'editorWarning.foreground': string;
	'editorInfo.foreground': string;
	'editorGutter.addedBackground': string;
	'editorGutter.modifiedBackground': string;
	'editorGutter.deletedBackground': string;
	'gitDecoration.addedResourceForeground': string;
	'gitDecoration.modifiedResourceForeground': string;
	'gitDecoration.deletedResourceForeground': string;
	'gitDecoration.untrackedResourceForeground': string;
	'gitDecoration.ignoredResourceForeground': string;
	'peekView.border': string;
	'peekViewEditor.background': string;
	'peekViewResult.background': string;
	'peekViewTitle.background': string;
	'notificationCenter.border': string;
	'notificationCenterHeader.background': string;
	'notifications.background': string;
	'notifications.border': string;
	'notificationLink.foreground': string;
	'settings.headerForeground': string;
	'settings.modifiedItemIndicator': string;
	'settings.focusedRowBackground': string;
	'settings.rowHoverBackground': string;
	'settings.focusedRowBorder': string;
	'settings.numberInputBackground': string;
	'settings.numberInputForeground': string;
	'settings.numberInputBorder': string;
	'settings.textInputBackground': string;
	'settings.textInputForeground': string;
	'settings.textInputBorder': string;
	'settings.checkboxBackground': string;
	'settings.checkboxForeground': string;
	'settings.checkboxBorder': string;
	'settings.dropdownBackground': string;
	'settings.dropdownForeground': string;
	'settings.dropdownBorder': string;
	'settings.dropdownListBorder': string;
	'textLink.foreground': string;
	'textLink.activeForeground': string;
	'textBlockQuote.background': string;
	'textBlockQuote.border': string;
	'textCodeBlock.background': string;
	'textPreformat.foreground': string;
	'textSeparator.foreground': string;
	'walkThrough.embeddedEditorBackground': string;
	'welcomePage.background': string;
};

export type VSCodeTheme = {
	$schema: typeof VSCodeThemeSchema;
	name: string;
	type: 'dark' | 'light';
	colors: VSCodeThemeColors;
	tokenColors: VSCodeTokenColor[];
};

export type SyntaxStyle = {
	color: string;
	fontStyle?: FontStyle;
	fontWeight?: number;
};

export type Player = {
	cursor: string;
	selection: string;
	background: string;
};

export type Appearance = 'dark' | 'light';

export type BackgroundAppearance = 'opaque' | 'blurred' | 'transparent';

export type ZedThemeStyle = {
	accents: string[];
	'vim.mode.text': string;
	'vim.normal.background': string;
	'vim.helix_normal.background': string;
	'vim.visual.background': string;
	'vim.helix_select.background': string;
	'vim.insert.background': string;
	'vim.visual_line.background': string;
	'vim.visual_block.background': string;
	'vim.replace.background': string;
	'background.appearance': BackgroundAppearance;
	border: string;
	'border.variant': string;
	'border.focused': string;
	'border.selected': string;
	'border.transparent': string;
	'border.disabled': string;
	'elevated_surface.background': string;
	'surface.background': string;
	background: string;
	'element.background': string;
	'element.hover': string;
	'element.active': string;
	'element.selected': string;
	'element.disabled': string;
	'drop_target.background': string;
	'ghost_element.background': string;
	'ghost_element.hover': string;
	'ghost_element.active': string;
	'ghost_element.selected': string;
	'ghost_element.disabled': string;
	text: string;
	'text.muted': string;
	'text.placeholder': string;
	'text.disabled': string;
	'text.accent': string;
	icon: string;
	'icon.muted': string;
	'icon.disabled': string;
	'icon.placeholder': string;
	'icon.accent': string;
	'status_bar.background': string;
	'title_bar.background': string;
	'title_bar.inactive_background': string;
	'toolbar.background': string;
	'tab_bar.background': string;
	'tab.inactive_background': string;
	'tab.active_background': string;
	'search.match_background': string;
	'panel.background': string;
	'panel.focused_border': string;
	'panel.indent_guide': string;
	'panel.indent_guide_active': string;
	'panel.indent_guide_hover': string;
	'panel.overlay_background': string;
	'pane.focused_border': string;
	'pane_group.border': string;
	'scrollbar.thumb.background': string;
	'scrollbar.thumb.hover_background': string;
	'scrollbar.thumb.active_background': string | null;
	'scrollbar.thumb.border': string | null;
	'scrollbar.track.background': string;
	'scrollbar.track.border': string;
	'minimap.thumb.background': string;
	'minimap.thumb.hover_background': string;
	'minimap.thumb.active_background': string;
	'minimap.thumb.border': string | null;
	'editor.foreground': string;
	'editor.background': string;
	'editor.gutter.background': string;
	'editor.subheader.background': string;
	'editor.active_line.background': string;
	'editor.highlighted_line.background': string | null;
	'editor.line_number': string;
	'editor.active_line_number': string;
	'editor.invisible': string;
	'editor.wrap_guide': string;
	'editor.active_wrap_guide': string;
	'editor.document_highlight.bracket_background': string;
	'editor.document_highlight.read_background': string;
	'editor.document_highlight.write_background': string;
	'editor.indent_guide': string;
	'editor.indent_guide_active': string;
	'terminal.background': string;
	'terminal.ansi.background': string;
	'terminal.foreground': string;
	'terminal.dim_foreground': string;
	'terminal.bright_foreground': string;
	'terminal.ansi.black': string;
	'terminal.ansi.white': string;
	'terminal.ansi.red': string;
	'terminal.ansi.green': string;
	'terminal.ansi.yellow': string;
	'terminal.ansi.blue': string;
	'terminal.ansi.magenta': string;
	'terminal.ansi.cyan': string;
	'terminal.ansi.bright_black': string;
	'terminal.ansi.bright_white': string;
	'terminal.ansi.bright_red': string;
	'terminal.ansi.bright_green': string;
	'terminal.ansi.bright_yellow': string;
	'terminal.ansi.bright_blue': string;
	'terminal.ansi.bright_magenta': string;
	'terminal.ansi.bright_cyan': string;
	'terminal.ansi.dim_black': string;
	'terminal.ansi.dim_white': string;
	'terminal.ansi.dim_red': string;
	'terminal.ansi.dim_green': string;
	'terminal.ansi.dim_yellow': string;
	'terminal.ansi.dim_blue': string;
	'terminal.ansi.dim_magenta': string;
	'terminal.ansi.dim_cyan': string;
	'link_text.hover': string;
	conflict: string;
	'conflict.border': string;
	'conflict.background': string;
	created: string;
	'created.border': string;
	'created.background': string;
	deleted: string;
	'deleted.border': string;
	'deleted.background': string;
	hidden: string;
	'hidden.border': string;
	'hidden.background': string;
	hint: string;
	'hint.border': string;
	'hint.background': string;
	ignored: string;
	'ignored.border': string;
	'ignored.background': string;
	modified: string;
	'modified.border': string;
	'modified.background': string;
	predictive: string;
	'predictive.border': string;
	'predictive.background': string;
	renamed: string;
	'renamed.border': string;
	'renamed.background': string;
	info: string;
	'info.border': string;
	'info.background': string;
	warning: string;
	'warning.border': string;
	'warning.background': string;
	error: string;
	'error.border': string;
	'error.background': string;
	success: string;
	'success.border': string;
	'success.background': string;
	unreachable: string;
	'unreachable.border': string;
	'unreachable.background': string;
	players: Player[];
	'version_control.added': string;
	'version_control.deleted': string;
	'version_control.modified': string;
	'version_control.renamed': string;
	'version_control.conflict': string;
	'version_control.conflict_marker.ours': string;
	'version_control.conflict_marker.theirs': string;
	'version_control.ignored': string;
	'debugger.accent': string;
	'editor.debugger_active_line.background': string;
	syntax: ZedSyntax;
};

export type ZedSyntax = {
	attribute: SyntaxStyle;
	boolean: SyntaxStyle;
	character: SyntaxStyle;
	'character.special': SyntaxStyle;
	comment: SyntaxStyle;
	'comment.doc': SyntaxStyle;
	'comment.documentation': SyntaxStyle;
	'comment.error': SyntaxStyle;
	'comment.hint': SyntaxStyle;
	'comment.note': SyntaxStyle;
	'comment.todo': SyntaxStyle;
	'comment.warning': SyntaxStyle;
	concept: SyntaxStyle;
	constant: SyntaxStyle;
	'constant.builtin': SyntaxStyle;
	'constant.macro': SyntaxStyle;
	constructor: SyntaxStyle;
	'diff.minus': SyntaxStyle;
	'diff.plus': SyntaxStyle;
	embedded: SyntaxStyle;
	emphasis: SyntaxStyle;
	'emphasis.strong': SyntaxStyle;
	enum: SyntaxStyle;
	field: SyntaxStyle;
	float: SyntaxStyle;
	function: SyntaxStyle;
	'function.decorator': SyntaxStyle;
	hint: SyntaxStyle;
	keyword: SyntaxStyle;
	'keyword.directive': SyntaxStyle;
	'keyword.directive.define': SyntaxStyle;
	'keyword.export': SyntaxStyle;
	label: SyntaxStyle;
	link_text: SyntaxStyle;
	link_uri: SyntaxStyle;
	module: SyntaxStyle;
	namespace: SyntaxStyle;
	number: SyntaxStyle;
	'number.float': SyntaxStyle;
	operator: SyntaxStyle;
	parameter: SyntaxStyle;
	parent: SyntaxStyle;
	predictive: SyntaxStyle;
	predoc: SyntaxStyle;
	preproc: SyntaxStyle;
	primary: SyntaxStyle;
	property: SyntaxStyle;
	punctuation: SyntaxStyle;
	'punctuation.bracket': SyntaxStyle;
	'punctuation.delimiter': SyntaxStyle;
	'punctuation.list_marker': SyntaxStyle;
	'punctuation.markup': SyntaxStyle;
	'punctuation.special': SyntaxStyle;
	'punctuation.special.symbol': SyntaxStyle;
	selector: SyntaxStyle;
	'selector.pseudo': SyntaxStyle;
	string: SyntaxStyle;
	'string.doc': SyntaxStyle;
	'string.documentation': SyntaxStyle;
	'string.escape': SyntaxStyle;
	'string.regex': SyntaxStyle;
	'string.regexp': SyntaxStyle;
	'string.special': SyntaxStyle;
	'string.special.path': SyntaxStyle;
	'string.special.symbol': SyntaxStyle;
	'string.special.url': SyntaxStyle;
	symbol: SyntaxStyle;
	tag: SyntaxStyle;
	'tag.attribute': SyntaxStyle;
	'tag.delimiter': SyntaxStyle;
	'tag.doctype': SyntaxStyle;
	text: SyntaxStyle;
	'text.literal': SyntaxStyle;
	title: SyntaxStyle;
	type: SyntaxStyle;
	'type.class.definition': SyntaxStyle;
	variable: SyntaxStyle;
	'variable.builtin': SyntaxStyle;
	'variable.member': SyntaxStyle;
	'variable.parameter': SyntaxStyle;
	'variable.special': SyntaxStyle;
	variant: SyntaxStyle;
};

export type ZedThemeEntry = {
	name: string;
	appearance: Appearance;
	style: ZedThemeStyle;
};

export const ZedThemeSchema = 'https://zed.dev/schema/themes/v0.2.0.json' as const;

export type ZedTheme = {
	$schema: typeof ZedThemeSchema;
	name: string;
	author: string;
	themes: ZedThemeEntry[];
};

export type ThemeResponse = VSCodeTheme | ZedTheme;

export type ZigPaletteResponse = {
	palette: Color[];
};
