export type SyntaxStyle = {
	color: string;
	fontStyle?: 'normal' | 'italic' | 'oblique';
	fontWeight?: number;
};

export type Player = {
	cursor: string;
	selection: string;
	background: string;
};

export type Appearance = 'dark' | 'light';

export type BackgroundAppearance = 'opaque' | 'blurred' | 'transparent';

export type ZedThemeStyle = {
	accents: string[];
	'vim.mode.text': string;
	'vim.normal.background': string;
	'vim.helix_normal.background': string;
	'vim.visual.background': string;
	'vim.helix_select.background': string;
	'vim.insert.background': string;
	'vim.visual_line.background': string;
	'vim.visual_block.background': string;
	'vim.replace.background': string;
	'background.appearance': BackgroundAppearance;
	border: string;
	'border.variant': string;
	'border.focused': string;
	'border.selected': string;
	'border.transparent': string;
	'border.disabled': string;
	'elevated_surface.background': string;
	'surface.background': string;
	background: string;
	'element.background': string;
	'element.hover': string;
	'element.active': string;
	'element.selected': string;
	'element.disabled': string;
	'drop_target.background': string;
	'ghost_element.background': string;
	'ghost_element.hover': string;
	'ghost_element.active': string;
	'ghost_element.selected': string;
	'ghost_element.disabled': string;
	text: string;
	'text.muted': string;
	'text.placeholder': string;
	'text.disabled': string;
	'text.accent': string;
	icon: string;
	'icon.muted': string;
	'icon.disabled': string;
	'icon.placeholder': string;
	'icon.accent': string;
	'status_bar.background': string;
	'title_bar.background': string;
	'title_bar.inactive_background': string;
	'toolbar.background': string;
	'tab_bar.background': string;
	'tab.inactive_background': string;
	'tab.active_background': string;
	'search.match_background': string;
	'panel.background': string;
	'panel.focused_border': string;
	'panel.indent_guide': string;
	'panel.indent_guide_active': string;
	'panel.indent_guide_hover': string;
	'panel.overlay_background': string;
	'pane.focused_border': string;
	'pane_group.border': string;
	'scrollbar.thumb.background': string;
	'scrollbar.thumb.hover_background': string;
	'scrollbar.thumb.active_background': string | null;
	'scrollbar.thumb.border': string | null;
	'scrollbar.track.background': string;
	'scrollbar.track.border': string;
	'minimap.thumb.background': string;
	'minimap.thumb.hover_background': string;
	'minimap.thumb.active_background': string;
	'minimap.thumb.border': string | null;
	'editor.foreground': string;
	'editor.background': string;
	'editor.gutter.background': string;
	'editor.subheader.background': string;
	'editor.active_line.background': string;
	'editor.highlighted_line.background': string | null;
	'editor.line_number': string;
	'editor.active_line_number': string;
	'editor.invisible': string;
	'editor.wrap_guide': string;
	'editor.active_wrap_guide': string;
	'editor.document_highlight.bracket_background': string;
	'editor.document_highlight.read_background': string;
	'editor.document_highlight.write_background': string;
	'editor.indent_guide': string;
	'editor.indent_guide_active': string;
	'terminal.background': string;
	'terminal.ansi.background': string;
	'terminal.foreground': string;
	'terminal.dim_foreground': string;
	'terminal.bright_foreground': string;
	'terminal.ansi.black': string;
	'terminal.ansi.white': string;
	'terminal.ansi.red': string;
	'terminal.ansi.green': string;
	'terminal.ansi.yellow': string;
	'terminal.ansi.blue': string;
	'terminal.ansi.magenta': string;
	'terminal.ansi.cyan': string;
	'terminal.ansi.bright_black': string;
	'terminal.ansi.bright_white': string;
	'terminal.ansi.bright_red': string;
	'terminal.ansi.bright_green': string;
	'terminal.ansi.bright_yellow': string;
	'terminal.ansi.bright_blue': string;
	'terminal.ansi.bright_magenta': string;
	'terminal.ansi.bright_cyan': string;
	'terminal.ansi.dim_black': string;
	'terminal.ansi.dim_white': string;
	'terminal.ansi.dim_red': string;
	'terminal.ansi.dim_green': string;
	'terminal.ansi.dim_yellow': string;
	'terminal.ansi.dim_blue': string;
	'terminal.ansi.dim_magenta': string;
	'terminal.ansi.dim_cyan': string;
	'link_text.hover': string;
	conflict: string;
	'conflict.border': string;
	'conflict.background': string;
	created: string;
	'created.border': string;
	'created.background': string;
	deleted: string;
	'deleted.border': string;
	'deleted.background': string;
	hidden: string;
	'hidden.border': string;
	'hidden.background': string;
	hint: string;
	'hint.border': string;
	'hint.background': string;
	ignored: string;
	'ignored.border': string;
	'ignored.background': string;
	modified: string;
	'modified.border': string;
	'modified.background': string;
	predictive: string;
	'predictive.border': string;
	'predictive.background': string;
	renamed: string;
	'renamed.border': string;
	'renamed.background': string;
	info: string;
	'info.border': string;
	'info.background': string;
	warning: string;
	'warning.border': string;
	'warning.background': string;
	error: string;
	'error.border': string;
	'error.background': string;
	success: string;
	'success.border': string;
	'success.background': string;
	unreachable: string;
	'unreachable.border': string;
	'unreachable.background': string;
	players: Player[];
	'version_control.added': string;
	'version_control.deleted': string;
	'version_control.modified': string;
	'version_control.renamed': string;
	'version_control.conflict': string;
	'version_control.conflict_marker.ours': string;
	'version_control.conflict_marker.theirs': string;
	'version_control.ignored': string;
	'debugger.accent': string;
	'editor.debugger_active_line.background': string;
	syntax: ZedSyntax;
};

export type ZedSyntax = {
	attribute: SyntaxStyle;
	boolean: SyntaxStyle;
	character: SyntaxStyle;
	'character.special': SyntaxStyle;
	comment: SyntaxStyle;
	'comment.doc': SyntaxStyle;
	'comment.documentation': SyntaxStyle;
	'comment.error': SyntaxStyle;
	'comment.hint': SyntaxStyle;
	'comment.note': SyntaxStyle;
	'comment.todo': SyntaxStyle;
	'comment.warning': SyntaxStyle;
	concept: SyntaxStyle;
	constant: SyntaxStyle;
	'constant.builtin': SyntaxStyle;
	'constant.macro': SyntaxStyle;
	constructor: SyntaxStyle;
	'diff.minus': SyntaxStyle;
	'diff.plus': SyntaxStyle;
	embedded: SyntaxStyle;
	emphasis: SyntaxStyle;
	'emphasis.strong': SyntaxStyle;
	enum: SyntaxStyle;
	field: SyntaxStyle;
	float: SyntaxStyle;
	function: SyntaxStyle;
	'function.decorator': SyntaxStyle;
	hint: SyntaxStyle;
	keyword: SyntaxStyle;
	'keyword.directive': SyntaxStyle;
	'keyword.directive.define': SyntaxStyle;
	'keyword.export': SyntaxStyle;
	label: SyntaxStyle;
	link_text: SyntaxStyle;
	link_uri: SyntaxStyle;
	module: SyntaxStyle;
	namespace: SyntaxStyle;
	number: SyntaxStyle;
	'number.float': SyntaxStyle;
	operator: SyntaxStyle;
	parameter: SyntaxStyle;
	parent: SyntaxStyle;
	predictive: SyntaxStyle;
	predoc: SyntaxStyle;
	preproc: SyntaxStyle;
	primary: SyntaxStyle;
	property: SyntaxStyle;
	punctuation: SyntaxStyle;
	'punctuation.bracket': SyntaxStyle;
	'punctuation.delimiter': SyntaxStyle;
	'punctuation.list_marker': SyntaxStyle;
	'punctuation.markup': SyntaxStyle;
	'punctuation.special': SyntaxStyle;
	'punctuation.special.symbol': SyntaxStyle;
	selector: SyntaxStyle;
	'selector.pseudo': SyntaxStyle;
	string: SyntaxStyle;
	'string.doc': SyntaxStyle;
	'string.documentation': SyntaxStyle;
	'string.escape': SyntaxStyle;
	'string.regex': SyntaxStyle;
	'string.regexp': SyntaxStyle;
	'string.special': SyntaxStyle;
	'string.special.path': SyntaxStyle;
	'string.special.symbol': SyntaxStyle;
	'string.special.url': SyntaxStyle;
	symbol: SyntaxStyle;
	tag: SyntaxStyle;
	'tag.attribute': SyntaxStyle;
	'tag.delimiter': SyntaxStyle;
	'tag.doctype': SyntaxStyle;
	text: SyntaxStyle;
	'text.literal': SyntaxStyle;
	title: SyntaxStyle;
	type: SyntaxStyle;
	'type.class.definition': SyntaxStyle;
	variable: SyntaxStyle;
	'variable.builtin': SyntaxStyle;
	'variable.member': SyntaxStyle;
	'variable.parameter': SyntaxStyle;
	'variable.special': SyntaxStyle;
	variant: SyntaxStyle;
};

export type ZedThemeEntry = {
	name: string;
	appearance: Appearance;
	style: ZedThemeStyle;
};

export const ZedThemeSchema = 'https://zed.dev/schema/themes/v0.2.0.json' as const;

export type ZedTheme = {
	$schema: typeof ZedThemeSchema;
	name: string;
	author: string;
	themes: ZedThemeEntry[];
};
